### ISSUE TITLE
Release pipeline: make images publicly available in ghcrio (release repo)

### ISSUE THREAD

**Issue by henderiw** [sdcio/docs#3]
separate repo
has to have access to the private repo

**Comment by hansthienpondt** [comment]
- Submitted PRs to all of the private repo's to use SSH_AUTH_SOCK for building the Docker images. (go mod download dependency). 
- Testing build pipeline.

**Comment by henderiw** [comment]
nightly branch -> uploaded to ghcr.io -> nightly build based on main
some issues with MS

**Comment by hansthienpondt** [comment]
nightly dev builds: done
goreleaser pipeline: done (push tag triggers the pipeline); binaries get built + docker image gets pushed.
TODO: push images public

**Comment by hansthienpondt** [comment]
Done!
