### ISSUE TITLE
`kubectl get sdc` troubleshooting

### ISSUE THREAD

**Issue by frederic-loui** [sdcio/docs#56]
Hi !

I'm testing `sdc` by following `Getting started` page:

- All seems to work as expected 
- No particular error occurs after each command

Except at the end `kubectl get sdc` output is:
```
❯ kubectl get sdc
NAME                                               READY   URL                                            REF        PROVIDER              VERSION
schema.inv.sdcio.dev/srl.nokia.sdcio.dev-23.10.1   True    https://github.com/nokia/srlinux-yang-models   v23.10.1   srl.nokia.sdcio.dev   23.10.1

NAME                                       READY
discoveryrule.inv.sdcio.dev/dev1-address   True

NAME                                            AGE
targetsyncprofile.inv.sdcio.dev/gnmi-onchange   25s

NAME                                                    AGE
targetconnectionprofile.inv.sdcio.dev/gnmi-skipverify   26s
```
while in the `Getting started` page i see:

```
NAME                                       READY
discoveryrule.inv.sdcio.dev/dev1-address   True

NAME                                               READY   URL                                            REF        PROVIDER              VERSION
schema.inv.sdcio.dev/srl.nokia.sdcio.dev-23.10.1   True    https://github.com/nokia/srlinux-yang-models   v23.10.1   srl.nokia.sdcio.dev   23.10.1

NAME                                                    AGE
targetconnectionprofile.inv.sdcio.dev/gnmi-skipverify   21m

NAME                       READY   DATASTORE   CONFIG   PROVIDER              ADDRESS              PLATFORM      SERIALNUMBER     MACADDRESS
target.inv.sdcio.dev/srl   True    True        True     srl.nokia.sdcio.dev   172.21.0.200:57400   7220 IXR-D3   Sim Serial No.   1A:AB:00:FF:00:00

NAME                                            AGE
targetsyncprofile.inv.sdcio.dev/gnmi-onchange   21m

```
Therefore there is a missing `cr`:
```
...
NAME                       READY   DATASTORE   CONFIG   PROVIDER              ADDRESS              PLATFORM      SERIALNUMBER     MACADDRESS
target.inv.sdcio.dev/srl   True    True        True     srl.nokia.sdcio.dev   172.21.0.200:57400   7220 IXR-D3   Sim Serial No.   1A:AB:00:FF:00:00
...
```
While trying to test [`Retrieve configuration`](https://docs.sdcio.dev/getting-started/basic-usage/#retrieve-configuration) section:
```
❯ kubectl get runningconfigs.config.sdcio.dev srl
Error from server (NotFound): runningconfigs.config.sdcio.dev "srl" not found
```
Natrurally the configuration retrieval related to ` network-instance` fails as `srl`is not found.
```
❯ kubectl get runningconfigs.config.sdcio.dev srl -ojsonpath="{.status.value.network-instance}" | jq
Error from server (NotFound): runningconfigs.config.sdcio.dev "srl" not found
```

Any suggestion/hint on how to troubleshoot this ?

Thanks in advance for your support/help !
Frederic

**Comment by frederic-loui** [comment]
As a follow-up it seems that `config-server` pod cannot establish grpc connection to `172.21.0.200` although I applied `iptables` rule. (As a side note i'm using WSL)

```
sudo iptables -I DOCKER-USER -o br-$(docker network inspect -f '{{ printf "%.12s" .ID }}' kind) -j ACCEPT
```
[config-server-6ffb4bdcc8-wqjnq.zip](https://github.com/user-attachments/files/15521767/config-server-6ffb4bdcc8-wqjnq.zip)

**Comment by henderiw** [comment]
The issue here is that the config-server GNMI connection to the SRL device is not working as you indicated.
So we need to find a way to connect the docker bridges from the kind cluster to the clab bridge.

I have this e.g.

henderiw@playground:~$ docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
4214df8cad99   bridge    bridge    local
8b5c6aa8216b   host      host      local
6ee98ca099d5   kind      bridge    local
5544d3b324df   kubenet   bridge    local
18ab0359dff8   none      null      local

kind always uses kind bridge and I used kubenet here for the clab.

henderiw@playground:~$ docker network inspect -f '{{ printf "%.12s" .ID }}' kind
6ee98ca099d5
henderiw@playground:~$ ip a br-6ee98ca099d5
Command "br-6ee98ca099d5" is unknown, try "ip address help".
henderiw@playground:~$ ip a | grep br-6ee98ca099d5
71: br-6ee98ca099d5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    inet 172.20.20.1/24 brd 172.20.20.255 scope global br-6ee98ca099d5
351: veth351a431@if350: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6ee98ca099d5 state UP group default

**Comment by steiler** [comment]
We could also deploy the kind cluster as part of the clab topo... Then they reside in the same network and would not need an iptables rule.

**Comment by frederic-loui** [comment]
> We could also deploy the kind cluster as part of the clab topo... Then they reside in the same network and would not need an iptables rule.

Thanks for your feedback and for pointing out the issue. If I understand correctly, the problem to solve here is to enable connectivity between the node SRL in `containerlab` and the pod from `kind` cluster.  Thus, the problem to solve is to enable connectivity between 2 docker containers, each container being in their own network.

Indeed attach `kind` into containerlab srl-lab might avoid the `iptables` rule.

I'll investigate this problem and see how this is not enable by iptables locally. There is maybe a config knob in the context of WSL context. Out of curiosity is the `Getting started` documentation always leads to a working state ?

**Comment by steiler** [comment]
No you would not need to deploy any extra interfaces. The kind node(s) would be attached to the mgmt docker network, which is also attached to the mgmt interfaces of the network nodes.

**Comment by henderiw** [comment]
If you do this in the club file like below. We will also have to update the discovery rule to match the subnet of the clab node.

```yaml
name: basic-usage

mgmt:
  network: kind

topology:
  kinds:
    nokia_srlinux:
      type: ixrd3
      image: ghcr.io/nokia/srlinux:23.10.1
  nodes:
    dev1:
      kind: nokia_srlinux
 ```
 
 
 This ip here we need to change: 172.21.0.200 to the output of this command
 docker inspect clab-basic-usage-dev1
```
apiVersion: inv.sdcio.dev/v1alpha1
kind: DiscoveryRule
metadata:
  name: dev1-address
  namespace: default
spec:
  period: 1m
  addresses:
  - address: 172.21.0.200
    hostName: dev1
  discoveryProfile:
    credentials: srl.nokia.sdcio.dev 
    connectionProfiles:
    - gnmi-skipverify
  targetConnectionProfiles:
  - credentials: srl.nokia.sdcio.dev 
    connectionProfile: gnmi-skipverify
    syncProfile: gnmi-onchange
  targetTemplate:
    labels:
      sdcio.dev/region: us-east
```

**Comment by frederic-loui** [comment]
I found an answer to the problem that would involve minimal change to the documentation:

## Solution to `kind` and `containerlab` communication from their respective docker network

* Find the `linux bridge interface` dedicated to `basic-usage` lab example in Getting started page

```
❯ docker network inspect -f '{{ printf "%.12s" .ID }}' basic-usage
37e8bb64ef43
```
* Find the `linux bridge interface` dedicated to `kind` 

```
❯ docker network inspect -f '{{ printf "%.12s" .ID }}' kind
e4d20d240e19
```
* Allow traffic back and forth issued from host belonging to each of these bridges respectively (Otherwise traffic will be blocked DOCKER-ISOLATION-STAGE-[x])

```
❯ sudo iptables -I DOCKER-USER -i br-e4d20d240e19 -o br-37e8bb64ef43 -j ACCEPT
❯ sudo iptables -I DOCKER-USER -i br-37e8bb64ef43 -o br-e4d20d240e19 -j ACCEPT
```
## Verification (Optional)

* Spin a basic linux container in `kind` such as the one below:

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
```
* log into the pod
```
kubectl exec -it ubuntu -- /bin/bash
```
* install ping
```
apt install inetutils-ping
```
* ping SRL node (should work after having applied iptables rules above)
```
root@ubuntu:/# ping 172.21.0.200 -c 5
PING 172.21.0.200 (172.21.0.200): 56 data bytes
64 bytes from 172.21.0.200: icmp_seq=0 ttl=62 time=13.209 ms
64 bytes from 172.21.0.200: icmp_seq=1 ttl=62 time=13.391 ms
64 bytes from 172.21.0.200: icmp_seq=2 ttl=62 time=12.021 ms
64 bytes from 172.21.0.200: icmp_seq=3 ttl=62 time=11.237 ms
64 bytes from 172.21.0.200: icmp_seq=4 ttl=62 time=19.536 ms
--- 172.21.0.200 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max/stddev = 11.237/13.879/19.536/2.937 ms
root@ubuntu:/#
```

* Finally `SDC/config-server` is now happy and DiscoveryRule can now create the `target->target.inv.sdcio.dev/dev1`
```
❯ kubectl get sdc
NAME                                               READY   URL                                            REF        PROVIDER              VERSION
schema.inv.sdcio.dev/srl.nokia.sdcio.dev-23.10.1   True    https://github.com/nokia/srlinux-yang-models   v23.10.1   srl.nokia.sdcio.dev   23.10.1

NAME                                       READY
discoveryrule.inv.sdcio.dev/dev1-address   True

NAME                                            AGE
targetsyncprofile.inv.sdcio.dev/gnmi-onchange   10h

NAME                                                    AGE
targetconnectionprofile.inv.sdcio.dev/gnmi-skipverify   10h

NAME                        READY   REASON   PROVIDER              ADDRESS              PLATFORM      SERIALNUMBER     MACADDRESS
target.inv.sdcio.dev/dev1   True             srl.nokia.sdcio.dev   172.21.0.200:57400   7220 IXR-D3   Sim Serial No.   1A:CF:00:FF:00:00
```

## A new problem occurs
* Config still cannot be fetched 
```
❯ kubectl get runningconfigs.config.sdcio.dev srl
Error from server (NotFound): runningconfigs.config.sdcio.dev "srl" not found
```

**Comment by henderiw** [comment]
The device is called dev1.

So with this it should work.

kubectl get runningconfigs.config.sdcio.dev dev1.

you can also do this.
kubectl get runningconfigs.config.sdcio.dev -> if you don't add a device you get all the devices that are registered. So you should see the dev1 and than we can do a specific request.

kubectl get runningconfigs.config.sdcio.dev dev1
kubectl get runningconfigs.config.sdcio.dev dev1 -o yaml -> for the details (also o json is possible)

**Comment by frederic-loui** [comment]
Fanstastic ! The command has now a meaning to me ...  
I was following the documentaton "à la lettre" 😅 ! All good now.
```
❯ kubectl get runningconfigs.config.sdcio.dev dev1
NAME
dev1
```

**Comment by henderiw** [comment]
Awesome thx for trying and we will use this issue to update the docs.

**Comment by frederic-loui** [comment]
[PR-57](https://github.com/sdcio/docs/pull/57)
Feel free to accept or not the PR as it is and merge it as per your convenience.

Thanks again for this great piece if software !
